apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-c965288e-test
  namespace: default
  labels:
    test-name: swagger-c965288e-test
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-c965288e-test
      file: swagger-c965288e-test.tar
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
    ports:
      - containerPort: 5665
        name: dashboard

---
apiVersion: v1
kind: Service
metadata:
  name: swagger-c965288e-test-service
spec:
  type: LoadBalancer
  selector:
    job-name: swagger-c965288e-test-1
  ports:
    - port: 5665
      targetPort: 5665