version: '3'
services:
  k6:
    build: .
    volumes:
      - ./final:/app/final
    environment:
      - K6_WEB_DASHBOARD=true
    command: ["final/device_test.js"]

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
