apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-375f41bf-test
  namespace: default
  labels:
    test-name: swagger-375f41bf-test
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-375f41bf-test
      file: swagger-375f41bf-test.tar
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"