apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-69572d54-test
  namespace: default
  labels:
    test-name: swagger-69572d54-test
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-69572d54-test
      file: swagger-69572d54-test.tar
  runner:
    image: ndammakian/xk6-images:1.0
    imagePullPolicy: IfNotPresent
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
    ports:
      - containerPort: 5665
        name: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-69572d54-test-service
spec:
  type: LoadBalancer
  selector:
    job-name: swagger-69572d54-test-1
  ports:
    - port: 5665
      targetPort: 5665