apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-d6901226-test
spec:
    parallelism: 1
    script:
        configMap:
            name: swagger-d6901226-test
            file: swagger-d6901226-test.tar
    runner:
        env:
        - name: K6_WEB_DASHBOARD
            value: "true"