apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger_1ff61ed3_test
  namespace: default
spec:
  script:
    archive:
      configMap:
        name: swagger_1ff61ed3_test
        file: archive.tar
  parallelism: 1