apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-759333de-test
  namespace: default
  labels:
    test-name: swagger-759333de-test
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-759333de-test
      file: swagger-759333de-test.tar
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-759333de-test-dashboard
  namespace: default
spec:
  selector:
    test-name: swagger-759333de-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5665
  type: LoadBalancer