apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-c5a4ff5d-test
  namespace: default
  labels:
    test-name: swagger-c5a4ff5d-test
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-c5a4ff5d-test
      file: swagger-c5a4ff5d-test.tar
  runner:
    image: k6-mqtt-dashboard
    imagePullPolicy: Allways
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"
    ports:
      - containerPort: 5665
        name: dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-c5a4ff5d-test-service
spec:
  type: LoadBalancer
  selector:
    job-name: swagger-c5a4ff5d-test-1
  ports:
    - port: 5665
      targetPort: 5665