apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-9d090abb-test
  namespace: default
spec:
  parallelism: 1
  script:
    configMap:
      name: swagger-9d090abb-test
      file: swagger-9d090abb-test.tar
  runner:
    env:
      - name: K6_WEB_DASHBOARD
        value: "true"