apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: swagger-19a5f44d-test
  namespace: default
spec:
  script:
    archive:
      configMap:
        name: swagger-19a5f44d-test
        file: swagger-19a5f44d-test.tar
  parallelism: 1